obj-$(CONFIG_PINCTRL_BCM63XX)	+= pinctrl-bcm63xx.o
obj-$(CONFIG_PINCTRL_BCM6328)	+= pinctrl-bcm6328.o
obj-$(CONFIG_PINCTRL_BCM6348)	+= pinctrl-bcm6348.o
obj-$(CONFIG_PINCTRL_BCM6358)	+= pinctrl-bcm6358.o
obj-$(CONFIG_PINCTRL_BCM6362)	+= pinctrl-bcm6362.o
obj-$(CONFIG_PINCTRL_BCM6368)	+= pinctrl-bcm6368.o
obj-$(CONFIG_PINCTRL_BCM63268)	+= pinctrl-bcm63268.o
